#!/usr/bin/env bash
# Displays the time for 12 horus and 59 minutes.
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 59

count=1
buffer=0
while [ "$buffer" -le 12 ]
do
    echo "Hour: $buffer"
    count=1
    while [ "$count" -le 59 ]
    do
        echo "$count"
	count=$((count + 1))
    done
    buffer=$((buffer + 1))
done
count=$count
